name: knoxvilleopendata
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - requests
  - jupyterlab
  - pypdf2
  - nodejs
  - numpy
  - matplotlib
  - pandas
  - geopandas
  # conda-forge
  - requests-cache
  - ipyleaflet
  - pip:
    - requests-html
