name: knoxvilleopendata
dependencies:
  - python=3.6
  - pip:
    - requests
    - requests-html
    - requests-cache
    - pypdf2
    - numpy
    - pandas
    - matplotlib
    - jupyterlab
    - nodejs
    - geopandas
    - ipyleaflet
