# pip is being used for most of installation
# it has been more stable for some unknown reason (geopandas)
name: knoxvilleopendata
channels:
  - conda-forge
dependencies:
  - python=3.6
  - ipyleaflet
  - jupyterlab
  - pip:
    - requests
    - requests-html
    - requests-cache
    - pypdf2
    - numpy
    - pandas
    - matplotlib
    - nodejs
    - geopandas
